apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "team1-demo-app1"
  annotations:
    github.com/project-slug: suxess-it/team1-demo-app1
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=demo-app1-prod'
    argocd/app-name: "adn-team1/demo-app1-prod"
    backstage.io/techdocs-ref: dir:.
    # kubecost.com/deployment-name: prod-demo-app-podtato-head-left-leg
    grafana/dashboard-selector: "(tags @> 'kubernetes-mixin')"
    kargo-project: "https://kargo.lab.suxessit.k8s.cloud.uibk.ac.at/project/team1-demo-app1-kargo-project"
    grafana/overview-dashboard: "https://grafana.lab.suxessit.k8s.cloud.uibk.ac.at/d/a87fb0d919ec0ea5f6543124e16c42a5/kubernetes-compute-resources-namespace-workloads?orgId=1&refresh=10s&var-datasource=default&var-cluster=sx-loki&var-namespace=team1-demo-app1-prod&var-type=All"
spec:
  type: service
  lifecycle: experimental
  owner: sx-authors
